In [1]:
import numpy as np
import pandas as pd 

In [2]:
training = pd.read_csv('d://training-final.csv',names=['S1','C1','S2','C2','S3','C3','S4','C4','S5','C5','hand'])
source_data = pd.read_csv('d://Semifinal-testing-final.csv', names=['S1','C1','S2','C2','S3','C3','S4','C4','S5','C5'])

In [3]:
training.head()

S1  C1 S2 C2 S3  C3 S4  C4 S5  C5  hand
0  H   Q  H  J  H  10  H   K  H   1     1
1  S   Q  S  K  S   J  S  10  S   1     1
2  D  10  D  J  D   Q  D   K  D   1     1
3  C   K  C  J  C  10  C   1  C   Q     1
4  C   J  C  K  C   1  C   Q  C  10     1

In [4]:
source_data.head()

S1  C1 S2 C2 S3 C3 S4 C4 S5 C5
0  D   6  C  2  D  9  S  2  S  9
1  C   3  S  Q  H  1  D  1  S  9
2  H   7  D  7  S  5  C  Q  C  4
3  D  10  D  7  H  3  H  9  C  3
4  S   K  H  6  H  3  D  4  H  9

In [5]:
training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 11 columns):
S1      6000 non-null object
C1      6000 non-null object
S2      6000 non-null object
C2      6000 non-null object
S3      6000 non-null object
C3      6000 non-null object
S4      6000 non-null object
C4      6000 non-null object
S5      6000 non-null object
C5      6000 non-null object
hand    6000 non-null int64
dtypes: int64(1), object(10)
memory usage: 515.7+ KB


In [6]:
source_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 10 columns):
S1    1000000 non-null object
C1    1000000 non-null object
S2    1000000 non-null object
C2    1000000 non-null object
S3    1000000 non-null object
C3    1000000 non-null object
S4    1000000 non-null object
C4    1000000 non-null object
S5    1000000 non-null object
C5    1000000 non-null object
dtypes: object(10)
memory usage: 76.3+ MB


In [7]:
training.shape

(6000, 11)

In [8]:
source_data.shape

(1000000, 10)

In [9]:
def transform_jkq(x):
    if x == 'J':
        return 11
    elif x == 'Q':
        return 12
    elif x == 'K':
        return 13
    else:
        return x
training['C1'] = training['C1'].apply(transform_jkq)
training['C2'] = training['C2'].apply(transform_jkq)
training['C3'] = training['C3'].apply(transform_jkq)
training['C4'] = training['C4'].apply(transform_jkq)
training['C5'] = training['C5'].apply(transform_jkq)
training[:5]


S1  C1 S2  C2 S3  C3 S4  C4 S5  C5  hand
0  H  12  H  11  H  10  H  13  H   1     1
1  S  12  S  13  S  11  S  10  S   1     1
2  D  10  D  11  D  12  D  13  D   1     1
3  C  13  C  11  C  10  C   1  C  12     1
4  C  11  C  13  C   1  C  12  C  10     1

In [10]:
source_data['C1'] = source_data['C1'].apply(transform_jkq)
source_data['C2'] = source_data['C2'].apply(transform_jkq)
source_data['C3'] = source_data['C3'].apply(transform_jkq)
source_data['C4'] = source_data['C4'].apply(transform_jkq)
source_data['C5'] = source_data['C5'].apply(transform_jkq)
source_data[:5]


S1  C1 S2  C2 S3 C3 S4  C4 S5 C5
0  D   6  C   2  D  9  S   2  S  9
1  C   3  S  12  H  1  D   1  S  9
2  H   7  D   7  S  5  C  12  C  4
3  D  10  D   7  H  3  H   9  C  3
4  S  13  H   6  H  3  D   4  H  9

In [11]:
encode_map = {'C':1, 'D':2, 'H':3,'S':4}
training['S1'] = training['S1'].map(encode_map)
training['S2'] = training['S2'].map(encode_map)
training['S3'] = training['S3'].map(encode_map)
training['S4'] = training['S4'].map(encode_map)
training['S5'] = training['S5'].map(encode_map)
training[:10]

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5  hand
0   3  12   3  11   3  10   3  13   3   1     1
1   4  12   4  13   4  11   4  10   4   1     1
2   2  10   2  11   2  12   2  13   2   1     1
3   1  13   1  11   1  10   1   1   1  12     1
4   1  11   1  13   1   1   1  12   1  10     1
5   3   3   3   4   3   2   3   5   3   6     3
6   3  11   3  12   3   9   3  10   3  13     3
7   4   4   4   2   4   1   4   3   4   5     3
8   2   7   2   6   2   5   2   9   2   8     3
9   1   3   1   4   1   1   1   2   1   5     3

In [12]:
source_data['S1'] = source_data['S1'].map(encode_map)
source_data['S2'] = source_data['S2'].map(encode_map)
source_data['S3'] = source_data['S3'].map(encode_map)
source_data['S4'] = source_data['S4'].map(encode_map)
source_data['S5'] = source_data['S5'].map(encode_map)
source_data[:10]

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5
0   2   6   1   2   2   9   4   2   4   9
1   1   3   4  12   3   1   2   1   4   9
2   3   7   2   7   4   5   1  12   1   4
3   2  10   2   7   3   3   3   9   1   3
4   4  13   3   6   3   3   2   4   3   9
5   4   1   4   8   4  11   1   4   1  13
6   1   7   1  10   4   3   4   6   3  11
7   2   1   3   3   1  13   1   7   4   7
8   2   3   4  12   2   1   1   5   2  10
9   4   4   2   5   3   1   3   9   1   9

In [13]:
def bincount2D_vectorized(a):    
    N = a.max()+1
    a_offs = a + np.arange(a.shape[0])[:,None]*N
    return np.bincount(a_offs.ravel(), minlength=a.shape[0]*N).reshape(-1,N)

S_training = training.iloc[:,[0,2,4,6,8]].astype(int)
S_training = pd.DataFrame(bincount2D_vectorized(S_training.values),columns=['suitCount0','suitCount1','suitCount2','suitCount3','suitCount4'])
training = pd.merge(training, S_training, how='left', left_index=True, right_index=True).drop(['suitCount0'],axis=1)


R_training = training.iloc[:,np.arange(1,10,2)].astype(int)
cols = ['rank{}'.format(x) for x in range(0,14,1)]
R_training = pd.DataFrame(bincount2D_vectorized(R_training.values),columns=cols)
training = pd.merge(training, R_training, how='left', left_index=True, right_index=True).drop(['rank0'],axis=1)

training.head()

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5   ...    rank4  rank5  rank6  rank7  \
0   3  12   3  11   3  10   3  13   3   1   ...        0      0      0      0   
1   4  12   4  13   4  11   4  10   4   1   ...        0      0      0      0   
2   2  10   2  11   2  12   2  13   2   1   ...        0      0      0      0   
3   1  13   1  11   1  10   1   1   1  12   ...        0      0      0      0   
4   1  11   1  13   1   1   1  12   1  10   ...        0      0      0      0   

   rank8  rank9  rank10  rank11  rank12  rank13  
0      0      0       1       1       1       1  
1      0      0       1       1       1       1  
2      0      0       1       1       1       1  
3      0      0       1       1       1       1  
4      0      0       1       1       1       1  

[5 rows x 28 columns]

In [14]:
S_source_data = source_data.iloc[:,[0,2,4,6,8]].astype(int)
S_source_data = pd.DataFrame(bincount2D_vectorized(S_source_data.values),columns=['suitCount0','suitCount1','suitCount2','suitCount3','suitCount4'])
source_data = pd.merge(source_data, S_source_data, how='left', left_index=True, right_index=True).drop(['suitCount0'],axis=1)


R_source_data = source_data.iloc[:,np.arange(1,10,2)].astype(int)
cols = ['rank{}'.format(x) for x in range(0,14,1)]
R_source_data = pd.DataFrame(bincount2D_vectorized(R_source_data.values),columns=cols)
source_data = pd.merge(source_data, R_source_data, how='left', left_index=True, right_index=True).drop(['rank0'],axis=1)

source_data.head()

S1  C1  S2  C2  S3 C3  S4  C4  S5 C5   ...    rank4  rank5  rank6  rank7  \
0   2   6   1   2   2  9   4   2   4  9   ...        0      0      1      0   
1   1   3   4  12   3  1   2   1   4  9   ...        0      0      0      0   
2   3   7   2   7   4  5   1  12   1  4   ...        1      1      0      2   
3   2  10   2   7   3  3   3   9   1  3   ...        0      0      0      1   
4   4  13   3   6   3  3   2   4   3  9   ...        1      0      1      0   

   rank8  rank9  rank10  rank11  rank12  rank13  
0      0      2       0       0       0       0  
1      0      1       0       0       1       0  
2      0      0       0       0       1       0  
3      0      1       1       0       0       0  
4      0      1       0       0       0       1  

[5 rows x 27 columns]

In [15]:
R_training = training.loc[:,['rank{}'.format(n) for n in range(1,14,1)]].astype(int)
R_training = pd.DataFrame(bincount2D_vectorized(R_training.values),columns=['rankCount{}'.format(n) for n in range(0,5,1)])
training = pd.merge(training, R_training, how='left', left_index=True, right_index=True).drop(['rankCount0'],axis=1)

training.head()

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5     ...      rank8  rank9  rank10  \
0   3  12   3  11   3  10   3  13   3   1     ...          0      0       1   
1   4  12   4  13   4  11   4  10   4   1     ...          0      0       1   
2   2  10   2  11   2  12   2  13   2   1     ...          0      0       1   
3   1  13   1  11   1  10   1   1   1  12     ...          0      0       1   
4   1  11   1  13   1   1   1  12   1  10     ...          0      0       1   

   rank11  rank12  rank13  rankCount1  rankCount2  rankCount3  rankCount4  
0       1       1       1           5           0           0           0  
1       1       1       1           5           0           0           0  
2       1       1       1           5           0           0           0  
3       1       1       1           5           0           0           0  
4       1       1       1           5           0           0           0  

[5 rows x 32 columns]

In [16]:
training[:5]

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5     ...      rank8  rank9  rank10  \
0   3  12   3  11   3  10   3  13   3   1     ...          0      0       1   
1   4  12   4  13   4  11   4  10   4   1     ...          0      0       1   
2   2  10   2  11   2  12   2  13   2   1     ...          0      0       1   
3   1  13   1  11   1  10   1   1   1  12     ...          0      0       1   
4   1  11   1  13   1   1   1  12   1  10     ...          0      0       1   

   rank11  rank12  rank13  rankCount1  rankCount2  rankCount3  rankCount4  
0       1       1       1           5           0           0           0  
1       1       1       1           5           0           0           0  
2       1       1       1           5           0           0           0  
3       1       1       1           5           0           0           0  
4       1       1       1           5           0           0           0  

[5 rows x 32 columns]

In [17]:
R_source_data = source_data.loc[:,['rank{}'.format(n) for n in range(1,14,1)]].astype(int)
R_source_data = pd.DataFrame(bincount2D_vectorized(R_source_data.values),columns=['rankCount{}'.format(n) for n in range(0,5,1)])
source_data = pd.merge(source_data, R_source_data, how='left', left_index=True, right_index=True).drop(['rankCount0'],axis=1)

source_data.head()

S1  C1  S2  C2  S3 C3  S4  C4  S5 C5     ...      rank8  rank9  rank10  \
0   2   6   1   2   2  9   4   2   4  9     ...          0      2       0   
1   1   3   4  12   3  1   2   1   4  9     ...          0      1       0   
2   3   7   2   7   4  5   1  12   1  4     ...          0      0       0   
3   2  10   2   7   3  3   3   9   1  3     ...          0      1       1   
4   4  13   3   6   3  3   2   4   3  9     ...          0      1       0   

   rank11  rank12  rank13  rankCount1  rankCount2  rankCount3  rankCount4  
0       0       0       0           1           2           0           0  
1       0       1       0           3           1           0           0  
2       0       1       0           3           1           0           0  
3       0       0       0           3           1           0           0  
4       0       0       1           5           0           0           0  

[5 rows x 31 columns]

In [18]:
#training['diff1_13'] = np.abs(training['rank1'] - training['rank13'])
for i in range(2,14,1):
    training['diff{}_{}'.format(i,i-1)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i-1)])
#training['diff13_1'] = np.abs(training['rank13'] - training['rank1'])

for i in range(3,14,1):
    training['diff{}_{}'.format(i, i - 2)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 2)])

for i in range(4,14,1):
    training['diff{}_{}'.format(i, i - 3)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 3)])

for i in range(5,14,1):
    training['diff{}_{}'.format(i, i - 4)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 4)])
    
for i in range(6,14,1):
    training['diff{}_{}'.format(i, i - 5)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 5)])
    
for i in range(7,14,1):
     training['diff{}_{}'.format(i, i - 6)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 6)])
for i in range(8,14,1):
    training['diff{}_{}'.format(i, i - 7)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 7)])

for i in range(9,14,1):
    training['diff{}_{}'.format(i, i - 8)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 8)])

for i in range(10,14,1):
    training['diff{}_{}'.format(i, i - 9)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 9)])
for i in range(11,14,1):
    training['diff{}_{}'.format(i, i - 10)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 10)])
for i in range(12,14,1):
    training['diff{}_{}'.format(i, i - 11)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 11)])
for i in range(13,14,1):
    training['diff{}_{}'.format(i, i - 12)] = np.abs(training['rank{}'.format(i)] - training['rank{}'.format(i - 12)])
  
training.head()

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5    ...     diff10_1  diff11_2  \
0   3  12   3  11   3  10   3  13   3   1    ...            0         1   
1   4  12   4  13   4  11   4  10   4   1    ...            0         1   
2   2  10   2  11   2  12   2  13   2   1    ...            0         1   
3   1  13   1  11   1  10   1   1   1  12    ...            0         1   
4   1  11   1  13   1   1   1  12   1  10    ...            0         1   

   diff12_3  diff13_4  diff11_1  diff12_2  diff13_3  diff12_1  diff13_2  \
0         1         1         0         1         1         0         1   
1         1         1         0         1         1         0         1   
2         1         1         0         1         1         0         1   
3         1         1         0         1         1         0         1   
4         1         1         0         1         1         0         1   

   diff13_1  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 110 columns]

In [19]:
#source_data['diff1_13'] = np.abs(source_data['rank1'] - source_data['rank13'])
for i in range(2,14,1):
    source_data['diff{}_{}'.format(i,i-1)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i-1)])
#training['diff13_1'] = np.abs(training['rank13'] - training['rank1'])


for i in range(3,14,1):
    source_data['diff{}_{}'.format(i, i - 2)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 2)])

for i in range(4,14,1):
    source_data['diff{}_{}'.format(i, i - 3)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 3)])


for i in range(5,14,1):
    source_data['diff{}_{}'.format(i, i - 4)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 4)])

    
for i in range(6,14,1):
    source_data['diff{}_{}'.format(i, i - 5)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 5)])

    
for i in range(7,14,1):
     source_data['diff{}_{}'.format(i, i - 6)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 6)])

for i in range(8,14,1):
    source_data['diff{}_{}'.format(i, i - 7)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 7)])

for i in range(9,14,1):
    source_data['diff{}_{}'.format(i, i - 8)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 8)])


for i in range(10,14,1):
    source_data['diff{}_{}'.format(i, i - 9)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 9)])

for i in range(11,14,1):
    source_data['diff{}_{}'.format(i, i - 10)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 10)])

for i in range(12,14,1):
    source_data['diff{}_{}'.format(i, i - 11)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 11)])

for i in range(13,14,1):
    source_data['diff{}_{}'.format(i, i - 12)] = np.abs(source_data['rank{}'.format(i)] - source_data['rank{}'.format(i - 12)])






source_data.head()

S1  C1  S2  C2  S3 C3  S4  C4  S5 C5    ...     diff10_1  diff11_2  \
0   2   6   1   2   2  9   4   2   4  9    ...            0         2   
1   1   3   4  12   3  1   2   1   4  9    ...            2         0   
2   3   7   2   7   4  5   1  12   1  4    ...            0         0   
3   2  10   2   7   3  3   3   9   1  3    ...            1         0   
4   4  13   3   6   3  3   2   4   3  9    ...            0         0   

   diff12_3  diff13_4  diff11_1  diff12_2  diff13_3  diff12_1  diff13_2  \
0         0         0         0         2         0         0         2   
1         0         0         2         1         1         1         0   
2         1         1         0         1         0         1         0   
3         2         0         0         0         2         0         0   
4         1         0         0         0         0         0         1   

   diff13_1  
0         0  
1         2  
2         0  
3         0  
4         1  

[5 rows x 109 columns]

In [20]:
training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Columns: 110 entries, S1 to diff13_1
dtypes: int64(105), object(5)
memory usage: 5.0+ MB


In [21]:
source_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Columns: 109 entries, S1 to diff13_1
dtypes: int64(104), object(5)
memory usage: 831.6+ MB


In [22]:
training = training.drop(['S1','C1','S2','C2','S3','C3','S4','C4','S5','C5'], axis=1)
#training = training.drop(['rank{}'.format(n) for n in range(1,14,1)], axis=1)
source_data = source_data.drop(['S1','C1','S2','C2','S3','C3','S4','C4','S5','C5'], axis=1)
#source_data = source_data.drop(['rank{}'.format(n) for n in range(1,14,1)], axis=1)

In [23]:
training[:5]

hand  suitCount1  suitCount2  suitCount3  suitCount4  rank1  rank2  rank3  \
0     1           0           0           5           0      1      0      0   
1     1           0           0           0           5      1      0      0   
2     1           0           5           0           0      1      0      0   
3     1           5           0           0           0      1      0      0   
4     1           5           0           0           0      1      0      0   

   rank4  rank5    ...     diff10_1  diff11_2  diff12_3  diff13_4  diff11_1  \
0      0      0    ...            0         1         1         1         0   
1      0      0    ...            0         1         1         1         0   
2      0      0    ...            0         1         1         1         0   
3      0      0    ...            0         1         1         1         0   
4      0      0    ...            0         1         1         1         0   

   diff12_2  diff13_3  diff12_1  diff13_2  diff13_1  
0         1         1         0         1         0  
1         1         1         0         1         0  
2         1         1         0         1         0  
3         1         1         0         1         0  
4         1         1         0         1         0  

[5 rows x 100 columns]

In [24]:
source_data[:5]

suitCount1  suitCount2  suitCount3  suitCount4  rank1  rank2  rank3  rank4  \
0           1           2           0           2      0      2      0      0   
1           1           1           1           2      2      0      1      0   
2           2           1           1           1      0      0      0      1   
3           1           2           2           0      0      0      2      0   
4           0           1           3           1      0      0      1      1   

   rank5  rank6    ...     diff10_1  diff11_2  diff12_3  diff13_4  diff11_1  \
0      0      1    ...            0         2         0         0         0   
1      0      0    ...            2         0         0         0         2   
2      1      0    ...            0         0         1         1         0   
3      0      0    ...            1         0         2         0         0   
4      0      1    ...            0         0         1         0         0   

   diff12_2  diff13_3  diff12_1  diff13_2  diff13_1  
0         2         0         0         2         0  
1         1         1         1         0         2  
2         1         0         1         0         0  
3         0         2         0         0         0  
4         0         0         0         1         1  

[5 rows x 99 columns]

In [25]:
X = training.drop(['hand'],axis=1)
y = training.hand

In [26]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=24)
X_resampled, y_resampled = ros.fit_sample(X, y)

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=34)

In [28]:
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier


mlp = MLPClassifier(hidden_layer_sizes=(80, 80, 80), solver='adam', activation='tanh', alpha = 0.0001, learning_rate_init=0.001, max_iter=300)
scores = cross_val_score(mlp, X_resampled, y_resampled, scoring='accuracy')
average_accuracy = np.mean(scores)*100
print('The average accuracy is {0:.10f}%'.format(average_accuracy))

The average accuracy is 99.9899023875%


In [29]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import log_loss, roc_auc_score, auc, roc_curve, classification_report, confusion_matrix, accuracy_score
#from sklearn.model_selection import KFold, train_test_split, StratifiedKFold, cross_val_score, GridSearchCV
mlp = MLPClassifier(hidden_layer_sizes=(60, 60, 50), solver='adam', activation='relu', alpha = 0.0001, learning_rate_init=0.001, max_iter=300)

mlp.fit(X_train, y_train)

y_pred = mlp.predict(X_test)

score = accuracy_score(y_test,y_pred)
print("CV accuracy: {}".format(score))

preds_probs = mlp.predict_proba(X_test)
loss = log_loss(y_test, preds_probs)
print('loss: ', loss)
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

CV accuracy: 0.999490056094
('loss: ', 0.0013198477468632727)
[[ 962    0    5    0    0    0    0    0    0    0]
 [   0  969    0    0    0    0    0    0    0    0]
 [   0    0  987    0    0    0    0    0    0    0]
 [   0    0    0  978    0    0    0    0    0    0]
 [   0    0    0    0  964    0    0    0    0    0]
 [   0    0    0    0    0 1003    0    0    0    0]
 [   0    0    0    0    0    0  973    0    0    0]
 [   0    0    0    0    0    0    0 1000    0    0]
 [   0    0    0    0    0    0    0    0  980    0]
 [   0    0    0    0    0    0    0    0    0  984]]
             precision    recall  f1-score   support

          0       1.00      0.99      1.00       967
          1       1.00      1.00      1.00       969
          2       0.99      1.00      1.00       987
          3       1.00      1.00      1.00       978
          4       1.00      1.00      1.00       964
          5       1.00      1.00      1.00      1003
          6       1.00      1.00   

In [30]:
#Max_iter的值
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier

best_score = 0
best_param = 0
for param in range(100, 1000, 100):
    mlp = MLPClassifier(hidden_layer_sizes=(50, 50, 15), solver='adam', activation='tanh', alpha = 0.0001, learning_rate_init=0.001, max_iter=param)
    scores = cross_val_score(mlp, X_resampled, y_resampled, scoring='accuracy')
    average_accuracy = np.mean(scores)*100
    print("Param: ", param)
    print('The average accuracy is {0:.10f}%'.format(average_accuracy))
    if best_score < average_accuracy:
        best_score = average_accuracy
        best_param = param
print("Best score: {0:.10f}%".format(best_score))
print('Best param: ', best_param)


('Param: ', 100)
The average accuracy is 99.9798081725%
('Param: ', 200)
The average accuracy is 99.9798115701%
('Param: ', 300)
The average accuracy is 99.9899023875%
('Param: ', 400)
The average accuracy is 99.9932693908%
('Param: ', 500)
The average accuracy is 99.9865387817%
('Param: ', 600)
The average accuracy is 99.9798081725%
('Param: ', 700)
The average accuracy is 99.9865319865%
('Param: ', 800)
The average accuracy is 99.9764411692%
('Param: ', 900)
The average accuracy is 99.9932693908%
Best score: 99.9932693908%
('Best param: ', 400)


In [31]:
#Max_iter的值
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier

best_score = 0
best_param = 0
for param in [0.0007, 0.0008, 0.0009, 0.001, 0.002, 0.003,]:
    mlp = MLPClassifier(hidden_layer_sizes=(50, 50, 15), solver='adam', activation='tanh', alpha = 0.0001, learning_rate_init=param, max_iter=300)
    scores = cross_val_score(mlp, X_resampled, y_resampled, scoring='accuracy')
    average_accuracy = np.mean(scores)*100
    print("Param: ", param)
    print('The average accuracy is {0:.10f}%'.format(average_accuracy))
    if best_score < average_accuracy:
        best_score = average_accuracy
        best_param = param
print("Best score: {0:.10f}%".format(best_score))
print('Best param: ', best_param)

('Param: ', 0.0007)
The average accuracy is 99.9932693908%
('Param: ', 0.0008)
The average accuracy is 99.9865319865%
('Param: ', 0.0009)
The average accuracy is 99.9629833485%
('Param: ', 0.001)
The average accuracy is 99.9865353841%
('Param: ', 0.002)
The average accuracy is 99.9898989899%
('Param: ', 0.003)
The average accuracy is 99.9764445668%
Best score: 99.9932693908%
('Best param: ', 0.0007)


In [32]:
#Max_iter的值
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier

best_score = 0
best_param = 0
for param in [0.00001, 0.00003, 0.00005,  0.00006, 0.00007,  0.00008,0.00009,0.0001, 0.0002, 0.0003, 0.0005, 0.0007, 0.001, 0.003]:
    mlp = MLPClassifier(hidden_layer_sizes=(50, 50, 15), solver='adam', activation='tanh', alpha = param, learning_rate_init=0.0007, max_iter=300)
    scores = cross_val_score(mlp, X_resampled, y_resampled, scoring='accuracy')
    average_accuracy = np.mean(scores)*100
    print("Param: ", param)
    print('The average accuracy is {0:.10f}%'.format(average_accuracy))
    if best_score < average_accuracy:
        best_score = average_accuracy
        best_param = param
print("Best score: {0:.10f}%".format(best_score))
print('Best param: ', best_param)

('Param: ', 1e-05)
The average accuracy is 99.9697173552%
('Param: ', 3e-05)
The average accuracy is 99.9798047750%
('Param: ', 5e-05)
The average accuracy is 99.9798047750%
('Param: ', 6e-05)
The average accuracy is 99.9764377716%
('Param: ', 7e-05)
The average accuracy is 99.9798047750%
('Param: ', 8e-05)
The average accuracy is 99.9663503518%
('Param: ', 9e-05)
The average accuracy is 99.9831717783%
('Param: ', 0.0001)
The average accuracy is 99.9932693908%
('Param: ', 0.0002)
The average accuracy is 99.9764411692%
('Param: ', 0.0003)
The average accuracy is 99.9831751759%
('Param: ', 0.0005)
The average accuracy is 99.9663537494%
('Param: ', 0.0007)
The average accuracy is 99.9899023875%
('Param: ', 0.001)
The average accuracy is 99.9898989899%
('Param: ', 0.003)
The average accuracy is 99.9798081725%
Best score: 99.9932693908%
('Best param: ', 0.0001)


In [34]:
best_score = 0
best_param_1 = 0
best_param_2 = 0
best_param_3 = 0

for layer_1 in range(10, 100, 10):
    for layer_2 in range(10, 100, 10):
        params = {
            'hidden_layer_sizes': (layer_1, layer_2), 
            'solver': 'adam', 
            'activation': 'relu', 
            'alpha': 0.0001, 
            'learning_rate_init': 0.0007,
            'max_iter': 400
        }
        mlp.set_params(**params)
        mlp_model = mlp.fit(X_train, y_train)

        preds_class = mlp_model.predict(X_test)
        preds_proba = mlp_model.predict_proba(X_test)

        score = accuracy_score(y_test,preds_class)
        loss = log_loss(y_test,preds_proba)
        print('------: {0}, {1}'.format(layer_1, layer_2))
        print("accuracy: {}".format(score))
        print("logloss: {}".format(loss))

        if best_score <= score or best_loss >= loss:
            best_score = score
            best_loss = loss
            best_param_1 = layer_1
            best_param_2 = layer_2
print('---------best result------------------')
print(best_param_1, best_param_2)
print("Best accuracy: {}".format(best_score))
print("Best logloss: {}".format(best_loss))


------: 10, 10
accuracy: 0.998776134625
logloss: 0.00439450104792
------: 10, 20
accuracy: 0.999694033656
logloss: 0.00228802881823
------: 10, 30
accuracy: 0.999286078531
logloss: 0.00350140217466
------: 10, 40
accuracy: 0.999388067313
logloss: 0.00207507443929
------: 10, 50
accuracy: 0.998878123406
logloss: 0.00354879879291
------: 10, 60
accuracy: 0.999694033656
logloss: 0.00205179896022
------: 10, 70
accuracy: 0.999286078531
logloss: 0.00195678804701
------: 10, 80
accuracy: 0.998980112188
logloss: 0.00426286459914
------: 10, 90
accuracy: 0.998980112188
logloss: 0.00306919743727
------: 20, 10
accuracy: 0.998572157063
logloss: 0.00514010953775
------: 20, 20
accuracy: 0.999592044875
logloss: 0.00180811449479
------: 20, 30
accuracy: 0.99918408975
logloss: 0.00312526521819
------: 20, 40
accuracy: 0.999490056094
logloss: 0.00226742353508
------: 20, 50
accuracy: 0.999694033656
logloss: 0.00126446441113
------: 20, 60
accuracy: 0.999286078531
logloss: 0.00198914761991
------: 20,

In [35]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics 
best_score = 0
best_param_1 = 0
best_param_2 = 0
best_param_3 = 0

mlp = MLPClassifier(random_state=15)

for layer_1 in range(10, 100, 10):
    for layer_2 in range(10, 100, 10):
         for layer_3 in range(10, 100, 10):
            params = {
                'hidden_layer_sizes': (layer_1, layer_2, layer_3), 
                'solver': 'adam', 
                'activation': 'relu', 
                'alpha': 0.0001, 
                'learning_rate_init': 0.001,
                'max_iter': 300
            }
            mlp.set_params(**params)
            mlp_model = mlp.fit(X_train, y_train)

            preds_class = mlp_model.predict(X_test)
            preds_proba = mlp_model.predict_proba(X_test)

            score = metrics.accuracy_score(y_test,preds_class)
            loss = metrics.log_loss(y_test,preds_proba)
            print('------: {0}, {1}, {2}'.format(layer_1, layer_2, layer_3))
            print("accuracy: {}".format(score))
            print("logloss: {}".format(loss))

            if best_score <= score or best_loss >= loss:
                best_score = score
                best_loss = loss
                best_param_1 = layer_1
                best_param_2 = layer_2
                best_param_3 = layer_3
print('---------best result------------------')
print(best_param_1, best_param_2, best_param_3)
print("Best accuracy: {}".format(best_score))
print("Best logloss: {}".format(best_loss))

------: 10, 10, 10
accuracy: 0.999388067313
logloss: 0.00182186338772
------: 10, 10, 20
accuracy: 0.998674145844
logloss: 0.00667614436871
------: 10, 10, 30
accuracy: 0.999490056094
logloss: 0.00217801715428
------: 10, 10, 40
accuracy: 0.999694033656
logloss: 0.00148892341313
------: 10, 10, 50
accuracy: 0.998776134625
logloss: 0.00500239174143
------: 10, 10, 60
accuracy: 0.999286078531
logloss: 0.00330303745043
------: 10, 10, 70
accuracy: 0.99918408975
logloss: 0.0025181735721
------: 10, 10, 80
accuracy: 0.999694033656
logloss: 0.00131206697638
------: 10, 10, 90
accuracy: 0.999592044875
logloss: 0.00117838152011
------: 10, 20, 10
accuracy: 0.998674145844
logloss: 0.00569694757466
------: 10, 20, 20
accuracy: 0.99918408975
logloss: 0.00211741878248
------: 10, 20, 30
accuracy: 0.999490056094
logloss: 0.00226094530646
------: 10, 20, 40
accuracy: 0.9983681795
logloss: 0.00543365463605
------: 10, 20, 50
accuracy: 0.999388067313
logloss: 0.00261870247847
------: 10, 20, 60
accura

In [29]:

from sklearn.neural_network import MLPClassifier
#Multilayer perceptron with 85 neurons as input and 10 neurons as output
mlp = MLPClassifier(hidden_layer_sizes=(80, 80, 80), solver='adam', activation='tanh', alpha = 0.0001, learning_rate_init=0.001, max_iter=300)
mlp.fit(X_resampled, y_resampled)
preds_class = mlp.predict(source_data)


In [30]:
mlp.loss_

0.0004068745203054807

In [31]:
result = pd.DataFrame(preds_class)

In [32]:
result

0
0       4
1       8
2       8
3       8
4       0
5       0
6       0
7       8
8       0
9       8
10      0
11      8
12      8
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      8
21      0
22      8
23      0
24      0
25      0
26      8
27      0
28      0
29      8
...    ..
999970  3
999971  0
999972  8
999973  8
999974  8
999975  0
999976  0
999977  8
999978  0
999979  8
999980  8
999981  9
999982  0
999983  8
999984  8
999985  0
999986  8
999987  8
999988  8
999989  8
999990  0
999991  0
999992  0
999993  0
999994  8
999995  0
999996  0
999997  8
999998  0
999999  8

[1000000 rows x 1 columns]

In [33]:
result_1 = result[0].apply(int)

In [34]:
result_2 = pd.DataFrame(result_1)

In [35]:
result_2.to_csv('H://data.txt', index=False, header=False)